### ISSUE TITLE
Error in VTKhandler.read()

### ISSUE THREAD

**Issue by mgirfogl** [mathLab/pydata#10]
vtkhandler.py, line 53, in read
    result['points'] = vtk_to_numpy(data.GetPoints().GetData())
AttributeError: 'NoneType' object has no attribute 'GetData'

**Comment by ndem0** [comment]
It looks a problem related with the file itself.
The method `GetPoints()` returns a `None` object, that for sure does not have the method `GetData()`.

Can you provide the file and the entire script, in order to reproduce the error?
